## Curriculum Vitae 
Below is a brief history of my career. For further inquires, email mhproconnect@gmail.com, or contact me via [Linkedin](https://www.linkedin.com/in/m-h-1b993a21a/)

### Work Experience 

##### Red Hat

 - Search Feature
 - Manage and Migrate DevOps Pipeline
 - Present to leadership and conferences

##### IBM 

 - Government Health and Human Services NLP Application
  - Social Work Language processing application. We developed tools to summarize and analyze documents generated by social workers in order to assist in managign the deluge of information required to provide assistance to those in need. Social workers deal with a LOT of text.  Case files, visit summaries, investiagtion reports. At IBM I helped create prototypes of proof of concept applications for various government social work agencies. We worked closely with subject matter experts and used cutting edge technologies to present our clients with solutions for their problems 
  - I implemented a feature like this https://scanslated.com/ to add into our Curam product. 

 - Recruitment and First year programs
  - Developer Buddy
  - Team building, orgainizing, competitions
 - Describe Slack summary project lead. Momeents, summarizes of long slack threads.
 - Developed a proposal and lead a team of junior engineers to develop an application for Watson Health GHHS
   - We didn't have any development resources, so I leveraged the entry level develop program to produce proof of concept material to present to our clients.  
 - Present to leadership and conferences

##### Interactive Intelligence
 - description. 
 - Intern and also Part time during grad school


##### Teaching Assitantships
 - List each course, with website and professor
 - COMP 101 introduction F16
 - COMP 283 Discrete Mathematics
 - COMP 585(?) Enabling Technologies, Gary Bishop

### Education
  - M.S. Computer Science, 2018, UNC Chapel Hill
    - Thesis in Bioinformatics (link to thesis paper)
    - Coursework in NLP, Security
    - Teaching Assistant Fellowships and Research Assitant work
  - 2014 REU Oregon State
    - Link to website with projects
    - Copy go ontology paper and put your name on papers
    - Plant ontology and GO boardgame visualazation
    - [DREU Website](https://dreuarchive.cra.org/2015/Hackett/blog.html) 
  - 2013 Protein Interactions with Kyla the PHD student. 
  - UNC Chapel Hill B.S. Computer Science + UNC Honors College Graduate 
  - High School Valedictorian (first black :) ) 

### Skills
  - Good at presentations
  - Communication, teaching new skills, onboarding
  - Team Building
  - Dev Ops, Debugging
  - Documentation/Writing
  - Customer Engagement, Good beside manner. 


### Contact info links 
   
 - [LinkedIn](https://www.linkedin.com/in/m-h-1b993a21a/)
 - [mqhackett](https://github.com/mqhackett) - Me at Red Hat
 - [quay.io](https://quay.io/user/mqhackett) - my old quay repo

[page 2](page2)
